package_assets:         on          # (on, off, always)
embed_assets:           on          # (on, off, datauri)
compress_assets:        on          # (on, off)
gzip_assets:            on          # (on, off)
template_function:      _.template  # (defaults to the built-in micro-templating)
package_path:           assets    # (defaults to assets)
javascript_compressor:  closure     # (yui, closure)
compressor_options:
compilation_level:      ADVANCED_OPTIMIZATIONS

javascripts:
  html5:
    - assets-src/javascripts/html5.js

  application:
    - assets-src/javascripts/vendor/*.js
    - assets-src/javascripts/functions.js

stylesheets:
  application:
    - assets-src/stylesheets/application.css